#!/usr/bin/env bash
set -e
set -o pipefail
set -u

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
# shellcheck disable=SC1090
source "$SCRIPT_DIR/lib/cloudrc"

main() {
  bash --version
}

main
